E
======================================================================
ERROR: lists.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: lists.tests
Traceback (most recent call last):
  File "C:\Anaconda3\lib\unittest\loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Anaconda3\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "C:\Users\chobits\Documents\site\tdd_django\lists\tests.py", line 6, in <module>
    from lists.models import Item
ImportError: cannot import name 'Item'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
